version: '3.1'

services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: snm
      MYSQL_USER: snm
      MYSQL_PASSWORD: snm
    ports:
      - 3306:3306

#  dbp:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: snm
#      POSTGRES_PASSWORD: snm
#      POSTGRES_DB: snm

  snm:
    image: simple-network-monitor
#    restart: always
    depends_on:
      - db
    #environment:
    #  DB_URL: jdbc:mysql://db:3306/snm?useSSL=false
    #  DB_USERNAME: snm
    #  DB_PASSWORD: snm
    #  DB_DRIVER: com.mysql.cj.jdbc.Driver
    #  DB_DIALECT: org.hibernate.dialect.MySQL5Dialect
    ports:
      - 8080:8080